'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'hi' | 'kn';

export const TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    'nav.home': 'Home',
    'nav.find_workers': 'Find Workers',
    'nav.upload_problem': 'Upload Problem',
    'nav.dashboard': 'Dashboard',
    'nav.sign_in': 'Sign In',
    'nav.get_started': 'Get Started',
    'nav.sign_out': 'Sign Out',
    'nav.profile_settings': 'Profile Settings',
    'nav.worker_dashboard': 'Worker Dashboard',
    
    // Auth / Onboarding
    'auth.welcome_back': 'Welcome back',
    'auth.sign_in_subtitle': 'Sign in to your account to continue',
    'auth.continue_google': 'Continue with Google',
    'auth.or_sign_in_email': 'or sign in with email',
    'auth.email_label': 'Email address',
    'auth.password_label': 'Password',
    'auth.sign_in_btn': 'Sign In',
    'auth.signing_in': 'Signing in...',
    'auth.no_account': 'Don\'t have an account?',
    'auth.create_one_free': 'Create one free',
    'auth.already_account': 'Already have an account?',
    'auth.sign_in': 'Sign in',
    'auth.get_started_hub': 'Get Started Hub',
    'auth.join_title': 'Join FixItNow',
    'auth.join_subtitle': 'Choose how you want to use the platform to get started with instant AI damage diagnosis and local pro bookings',
    'auth.homeowners_badge': 'Homeowners',
    'auth.homeowner_title': 'I Need Repairs / Help',
    'auth.homeowner_desc': 'Post household issues, snap photos or videos, get instant AI damage analysis, and hire top verified local pros.',
    'auth.homeowner_feature_1': 'AI Problem Diagnosis & Cost Estimates',
    'auth.homeowner_feature_2': 'GPS Pro Distance Matching (<30 mins)',
    'auth.homeowner_feature_3': 'Instant Tap-to-Book Local Pros',
    'auth.homeowner_cta': 'Sign Up as Homeowner / Client →',
    'auth.pro_badge': 'For Pros',
    'auth.worker_title': 'I\'m a Worker / Provider',
    'auth.worker_desc': 'List your trade services (plumbing, electrical, masonry), set custom hourly rates, and accept local jobs nearby.',
    'auth.worker_feature_1': 'Custom Trade Specialty Listing',
    'auth.worker_feature_2': 'Set Your Rates & Flexible Schedule',
    'auth.worker_feature_3': 'Receive Direct Client Job Bookings',
    'auth.worker_cta': 'Sign Up as Service Pro / Worker →',
    'auth.trust_dispatch': 'Avg. 15-min Dispatch',
    'auth.trust_verified': '100% Background Verified Pros',
    'auth.trust_ai': 'AI Vision Powered',
    'auth.homeowner': 'I Need Repairs / Help',
    'auth.worker': 'I\'m a Worker / Provider',
    'auth.homeowner_client': 'Homeowner / Client',
    'auth.service_pro_worker': 'Service Pro / Worker',
    'auth.register_as_customer': 'Register as Customer',
    'auth.customer_subtitle': 'Get instant AI damage diagnosis and hire local repair pros',
    'auth.register_as_worker': 'Register as Worker',
    'auth.worker_subtitle': 'List your specialty trade skills, set your rate & start receiving local jobs',
    'auth.sign_up_google': 'Sign up with Google',
    'auth.or_register_email': 'or register with email',
    'auth.full_name': 'Full Name',
    'auth.phone_number': 'Phone Number',
    'auth.email_address': 'Email Address',
    'auth.password': 'Password',
    'auth.select_primary_trade': 'Select Your Primary Trade',
    'auth.select_trade_placeholder': 'Select your trade specialty...',
    'auth.specify_trade_label': 'Specify Your Work / Trade (Not Listed)',
    'auth.create_customer_account': 'Create Customer Account →',
    'auth.create_worker_account': 'Create Worker Account →',
    'auth.connecting_google': 'Connecting to Google...',
    'auth.creating_account': 'Creating account...',
    
    // Sidebar Dock
    'dock.worker_console': 'Worker Console',
    'dock.incoming_requests': 'Incoming Requests',
    'dock.active_jobs': 'Active Jobs',
    'dock.completed_history': 'Completed History',
    'dock.location_radius': 'Location & Radius',
    'dock.trade_settings': 'Service Settings',
    'dock.account_settings': 'Account Settings',
    'dock.my_dashboard': 'My Dashboard',
    'dock.browse_workers': 'Browse Workers',
    'dock.ai_scanner': 'AI Issue Scanner',
    'dock.home_page': 'Home Page',
    'dock.find_workers': 'Find Workers',
    'dock.sign_in_register': 'Sign In / Register',
    'dock.console': 'Console',
    'dock.main_menu': 'Main Menu',

    // Dashboard
    'dashboard.welcome': 'Welcome back, {name}!',
    'dashboard.manage_requests': 'Manage your service requests, bookings, and active repairs.',
    'dashboard.file_new_problem': 'File New Problem',
    'dashboard.total_issues': 'Total Issues',
    'dashboard.active_repairs': 'Active Repairs',
    'dashboard.bookings': 'Bookings',
    'dashboard.no_issues': 'No posted issues yet',
    'dashboard.upload_photo': 'Upload a photo of your problem to get started.',
    'dashboard.file_problem': 'File Problem Now',
    'dashboard.no_bookings': 'No bookings yet',
    'dashboard.book_worker': 'Book a worker to see your bookings here.',
    'dashboard.posted_issues': 'My Posted Issues',
    'dashboard.booking_requests': 'Booking Requests',

    // Trades
    'trade.plumber': 'Plumber',
    'trade.electrician': 'Electrician',
    'trade.carpenter': 'Carpenter',
    'trade.painter': 'Painter',
    'trade.ac_tech': 'AC Technician',
    'trade.welder': 'Welder',
    'trade.mason': 'Mason',
    'trade.other': 'General Worker',

    // Workers page
    'workers.service_directory': 'Service Directory',
    'workers.find_verified_workers': 'Find Verified Workers',
    'workers.browse_subtitle': 'Browse and book skilled professionals in your local area.',
    'workers.all_trades': 'All Trades',
    'workers.search_placeholder': 'Search by worker name or city...',
    'workers.sort_by': 'Sort By',
    'workers.online_available': 'Online & Available',
    'workers.finding_workers': 'Finding workers...',
    'workers.no_matching_workers': 'No workers match your filters',
    'workers.clear_filters_hint': 'Try clearing your search query, toggling offline workers, or choosing a different trade category.',
    
    // Sort options
    'sort.distance': 'Distance (Nearest)',
    'sort.rating': 'Rating (Highest)',
    'sort.price_asc': 'Price (Lowest first)',
    'sort.experience': 'Experience (Highest)',

    // WorkerCard
    'card.verified': 'Verified',
    'card.reviews': 'reviews',
    'card.experience': 'experience',
    'card.away': 'away',
    'card.view_profile': 'View Profile',
    'card.book_now': 'Book Service Now',

    // Home landing page
    'home.hero_title': 'Your home problem, solved in minutes.',
    'home.hero_subtitle': 'Upload a photo or video. Our AI identifies the issue and instantly connects you with verified workers near you.',
    'home.upload_problem': 'Upload a Problem',
    'home.services_tag': 'Services',
    'home.services_title': 'Every service, one platform',
    'home.services_subtitle': 'From plumbing to painting — all your home service needs covered.',
    'home.how_it_works_tag': 'How It Works',
    'home.how_it_works_title': 'Fix it in 3 simple steps',
    'home.step1_title': 'Upload Photo or Video',
    'home.step1_desc': 'Take a photo or short video of the problem — pipe crack, broken socket, anything.',
    'home.step2_title': 'AI Detects the Issue',
    'home.step2_desc': 'Our AI engine identifies the problem, estimates dimensions, and classifies the trade needed.',
    'home.step3_title': 'Worker is Dispatched',
    'home.step3_desc': 'The right professional near you is matched and notified. Book in one tap.',
    'home.try_it_free': 'Try It Now — It\'s Free →',
    'home.ai_powered_tag': 'AI-Powered',
    'home.ai_title': 'Not just a directory. A smart problem solver.',
    'home.ai_subtitle': 'Our AI vision model analyzes your photo or video — detecting the problem type, estimating dimensions, judging severity, and selecting the exact right trade professional.',
    'home.upload_cta': 'Upload Your Problem →',
    'home.final_title': 'Got a problem at home?',
    'home.final_subtitle': 'Upload a photo now. AI does the rest.',
    'home.upload_free': 'Upload Problem — Free',
    'home.detecting_location': 'Detecting location...',
    'home.stat_jobs_completed': 'Jobs Completed',
    'home.stat_verified_workers': 'Verified Workers',
    'home.stat_satisfaction_rate': 'Satisfaction Rate',
    'home.stat_avg__response_time': 'Avg. Response Time',

    // AI Demo details
    'demo.pipe_detected': 'Leaking PVC Pipe Detected',
    'demo.urgent': '🔴 Urgent',
    'demo.plumbers_available': '3 plumbers available within 2km',
    'demo.required': 'Required',
    'demo.problem_lbl': 'Problem:',
    'demo.problem_val': 'Cracked PVC Water Pipe',
    'demo.dimension_lbl': 'Dimension:',
    'demo.dimension_val': '~25cm crack',
    'demo.severity_lbl': 'Severity:',
    'demo.confidence_lbl': 'Confidence:',
    'demo.reviews_tag': 'Reviews',
    'demo.reviews_title': 'Loved by homeowners',
    'home.ai_feature_1': 'Identifies 50+ home problem types',
    'home.ai_feature_2': 'Estimates size/length/area of damage',
    'home.ai_feature_3': 'Categorizes urgency level automatically',
    'home.ai_feature_4': 'Matches to nearest verified professional',

    // Upload page
    'upload.detect_problem': 'Detect Problem',
    'upload.whats_problem': 'What\'s the problem?',
    'upload.subtitle': 'Upload a photo or video of the issue. Our AI will detect the problem and find the right worker.',
    'upload.photo_tab': 'Photo',
    'upload.video_tab': 'Video',
    'upload.drag_photo': 'Upload a photo of the problem',
    'upload.drag_video': 'Upload a video of the problem',
    'upload.choose_photo': 'Choose Photo',
    'upload.take_photo': 'Take Photo',
    'upload.choose_video': 'Choose Video',
    'upload.record_video': 'Record Video',
    'upload.drag_drop_hint': 'Drag & drop or click to browse — max 20MB',
    'upload.tip_video_lighting': 'Ensure good lighting throughout',
    'upload.tip_video_duration': 'Keep video under 30 seconds',
    'upload.tip_video_focus': 'Focus on the damaged area',
    'upload.tip_video_angles': 'Show the problem from multiple angles',
    'upload.tip_video_steady': 'Hold phone steady, avoid shaking',
    'upload.tip_video_scale': 'Include a reference object for scale',
    'upload.tip_image_lighting': 'Ensure good lighting',
    'upload.tip_image_scale': 'Include something for scale (ruler, coin)',
    'upload.tip_image_focus': 'Focus on the damaged area',
    'upload.tip_image_angles': 'Take from multiple angles if possible',
    'upload.location_unavailable': 'Location unavailable — workers may be less accurate',
    'upload.remove': 'Remove',
    'upload.analyzing_video': 'Analyzing Video...',
    'upload.analyzing_photo': 'Analyzing Photo...',
    'upload.analyze_video_cta': '🤖 Analyze Video with AI →',
    'upload.analyze_photo_cta': '🤖 Analyze Photo with AI →',
    'upload.video_note': '💡 AI will watch the entire video to detect the problem, estimate dimensions, and assess urgency.',
    'upload.tips_title': 'Tips for best results',

    // Booking Page
    'book.tag': 'Book Worker',
    'book.title': 'Confirm Your Booking',
    'book.subtitle': 'Review professional details and choose your preferred visit time.',
    'book.step1_header': 'Schedule Visit',
    'book.step2_header': 'Location & Payment',
    'book.step_badge': 'Step {step} of 2',
    'book.hourly_rate': 'Hourly Rate',
    'book.experience': 'Experience',
    'book.locality': 'Locality',
    'book.reviews': 'reviews',
    'book.service_summary': 'Service Summary',
    'book.verified_background': 'Verified Background',
    'book.fair_price_guarantee': 'Fair Price Guarantee',
    'book.visit_date': 'Visit Date',
    'book.preferred_time': 'Preferred Time',
    'book.describe_issue': 'Describe Issue / Problem',
    'book.optional': 'Optional',
    'book.issue_placeholder': 'Briefly describe what needs fixing, any specific symptoms, or notes for the worker...',
    'book.booking_fee': 'Booking Fee',
    'book.free': 'FREE (₹0)',
    'book.est_rate': 'Est. Rate',
    'book.sign_in_continue': 'Sign In to Continue →',
    'book.next_step': 'Next: Location & Payment →',
    'book.service_address': 'Service Address',
    'book.detect_gps': 'Detect GPS Location',
    'book.address_placeholder': 'House / Flat No., Building, Street, Landmark...',
    'book.pincode_city': 'Pincode / City',
    'book.pincode_placeholder': 'e.g. 400001, Mumbai',
    'book.payment_method': 'Select Payment Method',
    'book.cash_payment': 'Cash / Pay After Service',
    'book.cash_desc': 'No upfront payment required today',
    'book.upi_payment': 'UPI / GPay / PhonePe',
    'book.upi_desc': 'Instant digital payment link',
    'book.card_payment': 'Credit / Debit Card',
    'book.card_desc': 'Visa, Mastercard, RuPay',
    'book.back': '← Back',
    'book.confirm_cta': 'Confirm & Book Worker →',
    'book.booking_in_progress': 'Booking...',
    'book.cancellation_note': 'Free cancellation before worker accepts. No charges until work begins.',
    'book.confirmed_title': 'Booking Confirmed!',
    'book.confirmed_subtitle': 'Your service request has been sent to the professional.',
    'book.go_to_dashboard': 'Go to Dashboard →',
    'book.back_to_home': 'Back to Home',

    // Worker Profile Page
    'wp.govt_verified': 'Govt ID Verified',
    'wp.specialist': 'Specialist',
    'wp.serving': 'Serving',
    'wp.per_hour': 'per hour',
    'wp.public_preview': 'Public Preview',
    'wp.how_others_view': 'How others view your profile.',
    'wp.edit_profile': 'Edit Profile →',
    'wp.book_now': 'Book {name} Now →',
    'wp.perf_highlights': 'Performance Highlights',
    'wp.rating': 'Rating',
    'wp.reviews': 'Reviews',
    'wp.experience': 'Experience',
    'wp.radius': 'Radius',
    'wp.about': 'About {name}',
    'wp.services_offered': 'Specialized Services Offered ({count})',
    'wp.trust_verification': 'Trust & Verification',
    'wp.bg_checked': 'Background Checked',
    'wp.fast_dispatch': 'Fast Dispatch (<30m)',
    'wp.working_hours': 'Mon-Sat (8AM - 8PM)',
    'wp.no_hidden_fees': 'No Hidden Fees',
    'wp.guarantee_title': 'FixItNow Service Guarantee',
    'wp.guarantee_desc': 'Every booking is protected. If the issue recurs within 7 days, we arrange a free follow-up visit.',
    'wp.customer_reviews': 'Customer Reviews ({count})',
    'wp.no_reviews': 'No reviews yet.',
    'wp.worker_not_found': 'Worker not found.',
    'wp.browse_workers': 'Browse Workers',
    'wp.yrs': 'Yrs',
    'wp.km': 'km',

    // Profile Settings Page
    'profile.account_preferences': 'Account Preferences',
    'profile.edit_profile': 'Edit Profile',
    'profile.manage_subtitle': 'Manage your personal settings, location information, and professional service preferences.',
    'profile.loading': 'Loading profile settings...',
    'profile.upload_photo': 'Upload Photo',
    'profile.hide_url': 'Hide URL input',
    'profile.paste_url': 'Or paste Image URL',
    'profile.service_provider': 'Service Provider',
    'profile.customer_account': 'Customer Account',
    'profile.member_since': 'Member Since',
    'profile.gps_location': 'GPS Location',
    'profile.mapped': 'Mapped',
    'profile.unmapped': 'Unmapped',
    'profile.selected_trade': 'Selected Trade',
    'profile.hourly_rate': 'Hourly Rate',
    'profile.service_radius': 'Service Radius',
    'profile.availability': 'Availability',
    'profile.online': 'Online',
    'profile.offline': 'Offline',
    'profile.personal_details': 'Personal Details',
    'profile.location_area': 'Location & Area',
    'profile.service_profile': 'Service Profile',
    'profile.account_details': 'Account Details',
    'profile.account_details_desc': 'Update your identity and phone contact information.',
    'profile.full_name': 'Full Name',
    'profile.full_name_placeholder': 'Enter your full name',
    'profile.phone_number': 'Phone Number',
    'profile.location_title': 'Location Address & Service City',
    'profile.location_desc': 'Used to calculate distance filters and show your profile to nearby customers.',
    'profile.city_label': 'City / Operating Locality',
    'profile.city_placeholder': 'e.g. Mumbai, Delhi, Bengaluru',
    'profile.mapping_gps': 'Mapping GPS...',
    'profile.auto_detect_gps': 'Auto-Detect GPS Coordinates',
    'profile.service_settings_title': 'Professional Service Profile Settings',
    'profile.service_settings_desc': 'Configure trade specialty, hourly rate, and service radius shown to customers.',
    'profile.select_trade': 'Select Trade Specialty',
    'profile.hourly_rate_label': 'Hourly Rate (₹/hr)',
    'profile.experience_label': 'Experience (Years)',
    'profile.radius_label': 'Service Area Radius (km)',
    'profile.availability_status': 'Availability Status',
    'profile.availability_desc': 'Controls if your profile is listed in active search results',
    'profile.bio_label': 'Professional Bio',
    'profile.bio_placeholder': 'Describe your service expertise, repair guarantees, and qualifications...',
    'profile.services_offered': 'Customized Services Offered',
    'profile.services_offered_desc': 'Select which specialized repair services you offer to homeowners in your area.',
    'profile.additional_custom': 'Additional Custom Services:',
    'profile.add_custom_placeholder': 'Add a custom service (e.g. Smart Lock Installation)...',
    'profile.add_service': '+ Add Service',
    'profile.saving': 'Saving Settings...',
    'profile.save_cta': 'Save Profile & Service Settings →',
  },
  hi: {
    // Navbar
    'nav.home': 'होम',
    'nav.find_workers': 'कामगार खोजें',
    'nav.upload_problem': 'समस्या अपलोड करें',
    'nav.dashboard': 'डैशबोर्ड',
    'nav.sign_in': 'साइन इन',
    'nav.get_started': 'शुरू करें',
    'nav.sign_out': 'साइन आउट',
    'nav.profile_settings': 'प्रोफ़ाइल सेटिंग्स',
    'nav.worker_dashboard': 'कामगार डैशबोर्ड',
    
    // Auth / Onboarding
    'auth.welcome_back': 'वापस स्वागत है',
    'auth.sign_in_subtitle': 'जारी रखने के लिए अपने खाते में साइन इन करें',
    'auth.continue_google': 'Google के साथ जारी रखें',
    'auth.or_sign_in_email': 'या ईमेल से साइन इन करें',
    'auth.email_label': 'ईमेल पता',
    'auth.password_label': 'पासवर्ड',
    'auth.sign_in_btn': 'साइन इन',
    'auth.signing_in': 'साइन इन हो रहा है...',
    'auth.no_account': 'क्या आपका खाता नहीं है?',
    'auth.create_one_free': 'मुफ़्त खाता बनाएं',
    'auth.already_account': 'क्या आपके पास पहले से खाता है?',
    'auth.sign_in': 'साइन इन करें',
    'auth.get_started_hub': 'गेट स्टार्टेड हब',
    'auth.join_title': 'FixItNow से जुड़ें',
    'auth.join_subtitle': 'त्वरित AI क्षति निदान और स्थानीय प्रो बुकिंग शुरू करने के लिए चुनें कि आप प्लेटफ़ॉर्म का उपयोग कैसे करना चाहते हैं',
    'auth.homeowners_badge': 'गृहस्वामी',
    'auth.homeowner_title': 'मुझे मरम्मत / मदद चाहिए',
    'auth.homeowner_desc': 'घरेलू समस्याएं पोस्ट करें, फोटो या वीडियो लें, त्वरित AI क्षति विश्लेषण प्राप्त करें और शीर्ष सत्यापित स्थानीय पेशेवरों को नियुक्त करें।',
    'auth.homeowner_feature_1': 'AI समस्या निदान और लागत अनुमान',
    'auth.homeowner_feature_2': 'जीपीएस प्रो दूरी मिलान (<30 मिनट)',
    'auth.homeowner_feature_3': 'त्वरित टैप-टू-बुक स्थानीय पेशेवर',
    'auth.homeowner_cta': 'गृहस्वामी / ग्राहक के रूप में साइन अप करें →',
    'auth.pro_badge': 'पेशेवरों के लिए',
    'auth.worker_title': 'मैं एक कामगार / प्रदाता हूँ',
    'auth.worker_desc': 'अपनी ट्रेड सेवाओं (नलसाजी, बिजली, चिनाई) को सूचीबद्ध करें, अपनी दरें निर्धारित करें और आसपास के नौकरियां स्वीकार करें।',
    'auth.worker_feature_1': 'कस्टम ट्रेड विशेषता लिस्टिंग',
    'auth.worker_feature_2': 'अपनी दरें और लचीला शेड्यूल निर्धारित करें',
    'auth.worker_feature_3': 'प्रत्यक्ष ग्राहक जॉब बुकिंग प्राप्त करें',
    'auth.worker_cta': 'सर्विस प्रो / कामगार के रूप में साइन अप करें →',
    'auth.trust_dispatch': 'औसत 15 मिनट में प्रेषण',
    'auth.trust_verified': '100% पृष्ठभूमि सत्यापित पेशेवर',
    'auth.trust_ai': 'AI विज़न द्वारा संचालित',
    'auth.homeowner': 'मुझे मरम्मत / मदद चाहिए',
    'auth.worker': 'मैं एक कामगार / प्रदाता हूँ',
    'auth.homeowner_client': 'गृहस्वामी / ग्राहक',
    'auth.service_pro_worker': 'सर्विस प्रो / कामगार',
    'auth.register_as_customer': 'ग्राहक के रूप में पंजीकरण करें',
    'auth.customer_subtitle': 'त्वरित AI क्षति निदान प्राप्त करें और स्थानीय मरम्मत पेशेवरों को नियुक्त करें',
    'auth.register_as_worker': 'कामगार के रूप में पंजीकरण करें',
    'auth.worker_subtitle': 'अपने विशेष कौशल सूचीबद्ध करें, अपनी दर निर्धारित करें और स्थानीय नौकरियां प्राप्त करना शुरू करें',
    'auth.sign_up_google': 'Google के साथ साइन अप करें',
    'auth.or_register_email': 'या ईमेल से पंजीकरण करें',
    'auth.full_name': 'पूरा नाम',
    'auth.phone_number': 'फोन नंबर',
    'auth.email_address': 'ईमेल पता',
    'auth.password': 'पासवर्ड',
    'auth.select_primary_trade': 'अपनी प्राथमिक श्रेणी चुनें',
    'auth.select_trade_placeholder': 'अपनी ट्रेड विशेषता चुनें...',
    'auth.specify_trade_label': 'अपना काम / ट्रेड निर्दिष्ट करें (सूचीबद्ध नहीं)',
    'auth.create_customer_account': 'ग्राहक खाता बनाएं →',
    'auth.create_worker_account': 'कामगार खाता बनाएं →',
    'auth.connecting_google': 'Google से जुड़ रहा है...',
    'auth.creating_account': 'खाता बनाया जा रहा है...',
    
    // Sidebar Dock
    'dock.worker_console': 'कामगार कंसोल',
    'dock.incoming_requests': 'आने वाले अनुरोध',
    'dock.active_jobs': 'सक्रिय कार्य',
    'dock.completed_history': 'पूरा इतिहास',
    'dock.location_radius': 'स्थान और दायरा',
    'dock.trade_settings': 'सेवा सेटिंग्स',
    'dock.account_settings': 'खाता सेटिंग्स',
    'dock.my_dashboard': 'मेरा डैशबोर्ड',
    'dock.browse_workers': 'कामगार खोजें',
    'dock.ai_scanner': 'AI समस्या स्कैनर',
    'dock.home_page': 'होम पेज',
    'dock.find_workers': 'कामगार खोजें',
    'dock.sign_in_register': 'साइन इन / रजिस्टर',
    'dock.console': 'कंसोल',
    'dock.main_menu': 'मुख्य मेनू',

    // Dashboard
    'dashboard.welcome': 'वापस स्वागत है, {name}!',
    'dashboard.manage_requests': 'अपने सेवा अनुरोधों, बुकिंग और सक्रिय मरम्मत का प्रबंधन करें।',
    'dashboard.file_new_problem': 'नई समस्या दर्ज करें',
    'dashboard.total_issues': 'कुल समस्याएं',
    'dashboard.active_repairs': 'सक्रिय मरम्मत',
    'dashboard.bookings': 'बुकिंग',
    'dashboard.no_issues': 'अभी तक कोई पोस्ट की गई समस्या नहीं है',
    'dashboard.upload_photo': 'शुरू करने के लिए अपनी समस्या का एक फ़ोटो अपलोड करें।',
    'dashboard.file_problem': 'समस्या अभी दर्ज करें',
    'dashboard.no_bookings': 'अभी तक कोई बुकिंग नहीं है',
    'dashboard.book_worker': 'अपनी बुकिंग देखने के लिए किसी कामगार को बुक करें।',
    'dashboard.posted_issues': 'मेरी पोस्ट की गई समस्याएं',
    'dashboard.booking_requests': 'बुकिंग अनुरोध',

    // Trades
    'trade.plumber': 'नलसाज (Plumber)',
    'trade.electrician': 'बिजली मिस्त्री (Electrician)',
    'trade.carpenter': 'बढ़ई (Carpenter)',
    'trade.painter': 'चित्रकार (Painter)',
    'trade.ac_tech': 'एसी तकनीशियन (AC Tech)',
    'trade.welder': 'वेल्डर (Welder)',
    'trade.mason': 'राजमिस्त्री (Mason)',
    'trade.other': 'सामान्य कामगार',

    // Workers page
    'workers.service_directory': 'सेवा निर्देशिका',
    'workers.find_verified_workers': 'सत्यापित कामगार खोजें',
    'workers.browse_subtitle': 'अपने स्थानीय क्षेत्र में कुशल पेशेवरों को खोजें और बुक करें।',
    'workers.all_trades': 'सभी श्रेणियां',
    'workers.search_placeholder': 'कामगार का नाम या शहर खोजें...',
    'workers.sort_by': 'क्रमबद्ध करें',
    'workers.online_available': 'ऑनलाइन और उपलब्ध',
    'workers.finding_workers': 'कामगार खोजे जा रहे हैं...',
    'workers.no_matching_workers': 'कोई कामगार आपके फ़िल्टर से मेल नहीं खाता',
    'workers.clear_filters_hint': 'अपनी खोज क्वेरी को हटाने, ऑफ़लाइन कामगारों को देखने या कोई अन्य श्रेणी चुनने का प्रयास करें।',
    
    // Sort options
    'sort.distance': 'दूरी (निकटतम)',
    'sort.rating': 'रेटिंग (उच्चतम)',
    'sort.price_asc': 'मूल्य (कम से अधिक)',
    'sort.experience': 'अनुभव (अधिकतम)',

    // WorkerCard
    'card.verified': 'सत्यापित',
    'card.reviews': 'समीक्षाएं',
    'card.experience': 'अनुभव',
    'card.away': 'दूर',
    'card.view_profile': 'प्रोफ़ाइल देखें',
    'card.book_now': 'अभी बुक करें',

    // Home landing page
    'home.hero_title': 'आपके घर की समस्या, मिनटों में हल।',
    'home.hero_subtitle': 'एक फोटो या वीडियो अपलोड करें। हमारा AI समस्या की पहचान करता है और तुरंत आपको आपके पास के सत्यापित कामगारों से जोड़ता है।',
    'home.upload_problem': 'समस्या अपलोड करें',
    'home.services_tag': 'सेवाएं',
    'home.services_title': 'हर श्रेणी, एक मंच',
    'home.services_subtitle': 'प्लंबिंग से लेकर पेंटिंग तक — आपकी सभी घरेलू सेवाएं एक ही स्थान पर उपलब्ध हैं।',
    'home.how_it_works_tag': 'यह कैसे काम करता है',
    'home.how_it_works_title': '3 आसान चरणों में ठीक करें',
    'home.step1_title': 'फोटो या वीडियो अपलोड करें',
    'home.step1_desc': 'समस्या का एक फोटो या छोटा वीडियो लें — पाइप में दरार, टूटा हुआ सॉकेट, कुछ भी।',
    'home.step2_title': 'AI समस्या का पता लगाता है',
    'home.step2_desc': 'हमारा AI इंजन समस्या की पहचान करता है, आयामों का अनुमान लगाता है, और आवश्यक श्रेणी को वर्गीकृत करता है।',
    'home.step3_title': 'कामगार भेजा जाता है',
    'home.step3_desc': 'आपके पास के सही पेशेवर का मिलान किया जाता है और उन्हें सूचित किया जाता है। एक टैप में बुक करें।',
    'home.try_it_free': 'अभी प्रयास करें — यह मुफ़्त है →',
    'home.ai_powered_tag': 'AI-संचालित',
    'home.ai_title': 'केवल एक निर्देशिका नहीं। एक स्मार्ट समस्या समाधानकर्ता।',
    'home.ai_subtitle': 'हमारा AI विज़न मॉडल आपके फ़ोटो या वीडियो का विश्लेषण करता है — समस्या के प्रकार का पता लगाता है, आयामों का अनुमान लगाता है, गंभीरता का आकलन करता है, और सही कामगार का चयन करता है।',
    'home.upload_cta': 'अपनी समस्या अपलोड करें →',
    'home.final_title': 'घर में कोई समस्या है?',
    'home.final_subtitle': 'अभी एक फोटो अपलोड करें। बाकी काम AI कर देगा।',
    'home.upload_free': 'समस्या अपलोड करें — मुफ़्त',
    'home.detecting_location': 'स्थान खोजा जा रहा है...',
    'home.stat_jobs_completed': 'काम पूरे किए गए',
    'home.stat_verified_workers': 'सत्यापित कामगार',
    'home.stat_satisfaction_rate': 'संतुष्टि दर',
    'home.stat_avg__response_time': 'औसत प्रतिक्रिया समय',

    // AI Demo details
    'demo.pipe_detected': 'लीकिंग पीवीसी पाइप का पता चला',
    'demo.urgent': '🔴 अति आवश्यक',
    'demo.plumbers_available': '2 किमी के भीतर 3 नलसाज उपलब्ध हैं',
    'demo.required': 'की आवश्यकता',
    'demo.problem_lbl': 'समस्या:',
    'demo.problem_val': 'टूटा हुआ पीवीसी पानी का पाइप',
    'demo.dimension_lbl': 'आयाम:',
    'demo.dimension_val': '~25 सेमी दरार',
    'demo.severity_lbl': 'गंभीरता:',
    'demo.confidence_lbl': 'विश्वास:',
    'demo.reviews_tag': 'समीक्षाएं',
    'demo.reviews_title': 'गृहस्वामियों द्वारा पसंद किया गया',
    'home.ai_feature_1': '50+ घरेलू समस्याओं के प्रकारों की पहचान करता है',
    'home.ai_feature_2': 'क्षति के आकार/लंबाई/क्षेत्रफल का अनुमान लगाता है',
    'home.ai_feature_3': 'तत्काल स्तर को स्वचालित रूप से वर्गीकृत करता है',
    'home.ai_feature_4': 'निकटतम सत्यापित पेशेवर से मेल खाता है',

    // Upload page
    'upload.detect_problem': 'समस्या का पता लगाएं',
    'upload.whats_problem': 'क्या समस्या है?',
    'upload.subtitle': 'समस्या का एक फोटो या वीडियो अपलोड करें। हमारा AI समस्या का पता लगाएगा और सही कामगार ढूंढेगा।',
    'upload.photo_tab': 'फोटो',
    'upload.video_tab': 'वीडियो',
    'upload.drag_photo': 'समस्या की एक फोटो अपलोड करें',
    'upload.drag_video': 'समस्या का एक वीडियो अपलोड करें',
    'upload.choose_photo': 'फोटो चुनें',
    'upload.take_photo': 'फोटो लें',
    'upload.choose_video': 'वीडियो चुनें',
    'upload.record_video': 'वीडियो रिकॉर्ड करें',
    'upload.drag_drop_hint': 'खींचें और छोड़ें या ब्राउज़ करने के लिए क्लिक करें — अधिकतम 20MB',
    'upload.tip_video_lighting': 'पूरे वीडियो में अच्छी रोशनी सुनिश्चित करें',
    'upload.tip_video_duration': 'वीडियो 30 सेकंड से कम रखें',
    'upload.tip_video_focus': 'क्षतिग्रस्त क्षेत्र पर ध्यान केंद्रित करें',
    'upload.tip_video_angles': 'समस्या को विभिन्न कोणों से दिखाएं',
    'upload.tip_video_steady': 'फोन स्थिर रखें, हिलने से बचें',
    'upload.tip_video_scale': 'आकार के लिए एक संदर्भ वस्तु शामिल करें',
    'upload.tip_image_lighting': 'अच्छी रोशनी सुनिश्चित करें',
    'upload.tip_image_scale': 'आकार के लिए कुछ शामिल करें (पैमाना, सिक्का)',
    'upload.tip_image_focus': 'क्षतिग्रस्त क्षेत्र पर ध्यान केंद्रित करें',
    'upload.tip_image_angles': 'यदि संभव हो तो विभिन्न कोणों से लें',
    'upload.location_unavailable': 'स्थान अनुपलब्ध — हो सकता है कामगारों की खोज कम सटीक हो',
    'upload.remove': 'हटाएं',
    'upload.analyzing_video': 'वीडियो का विश्लेषण किया जा रहा है...',
    'upload.analyzing_photo': 'फोटो का विश्लेषण किया जा रहा है...',
    'upload.analyze_video_cta': '🤖 AI के साथ वीडियो का विश्लेषण करें →',
    'upload.analyze_photo_cta': '🤖 AI के साथ फोटो का विश्लेषण करें →',
    'upload.video_note': '💡 AI समस्या का पता लगाने, आयामों का अनुमान लगाने और तात्कालिकता का आकलन करने के लिए पूरे वीडियो को देखेगा।',
    'upload.tips_title': 'सर्वोत्तम परिणामों के लिए सुझाव',

    // Booking Page
    'book.tag': 'कामगार बुक करें',
    'book.title': 'अपनी बुकिंग की पुष्टि करें',
    'book.subtitle': 'पेशेवर विवरण की समीक्षा करें और अपनी पसंदीदा यात्रा का समय चुनें।',
    'book.step1_header': 'यात्रा का समय निर्धारित करें',
    'book.step2_header': 'स्थान और भुगतान',
    'book.step_badge': 'चरण {step} / 2',
    'book.hourly_rate': 'प्रति घंटा दर',
    'book.experience': 'अनुभव',
    'book.locality': 'स्थान',
    'book.reviews': 'समीक्षाएं',
    'book.service_summary': 'सेवा सारांश',
    'book.verified_background': 'सत्यापित पृष्ठभूमि',
    'book.fair_price_guarantee': 'उचित मूल्य गारंटी',
    'book.visit_date': 'यात्रा की तिथि',
    'book.preferred_time': 'पसंदीदा समय',
    'book.describe_issue': 'समस्या का वर्णन करें',
    'book.optional': 'वैकल्पिक',
    'book.issue_placeholder': 'संक्षेप में बताएं कि क्या ठीक करने की आवश्यकता है या कामगार के लिए कोई निर्देश...',
    'book.booking_fee': 'बुकिंग शुल्क',
    'book.free': 'मुफ़्त (₹0)',
    'book.est_rate': 'अनुमानित दर',
    'book.sign_in_continue': 'आगे बढ़ने के लिए साइन इन करें →',
    'book.next_step': 'अगला: स्थान और भुगतान →',
    'book.service_address': 'सेवा का पता',
    'book.detect_gps': 'जीपीएस स्थान खोजें',
    'book.address_placeholder': 'मकान/फ़्लैट नं., गली, लैंडमार्क...',
    'book.pincode_city': 'पिनकोड / शहर',
    'book.pincode_placeholder': 'उदा. 400001, मुंबई',
    'book.payment_method': 'भुगतान विधि चुनें',
    'book.cash_payment': 'नकद / काम के बाद भुगतान',
    'book.cash_desc': 'आज किसी अग्रिम भुगतान की आवश्यकता नहीं है',
    'book.upi_payment': 'यूपीआई / जीपे / फोनपे',
    'book.upi_desc': 'त्वरित डिजिटल भुगतान लिंक',
    'book.card_payment': 'क्रेडिट / डेबिट कार्ड',
    'book.card_desc': 'वीज़ा, मास्टरकार्ड, रुपे',
    'book.back': '← वापस',
    'book.confirm_cta': 'पुष्टि करें और कामगार बुक करें →',
    'book.booking_in_progress': 'बुकिंग हो रही है...',
    'book.cancellation_note': 'कामगार द्वारा स्वीकार करने से पहले मुफ़्त रद्द करें। काम शुरू होने तक कोई शुल्क नहीं।',
    'book.confirmed_title': 'बुकिंग की पुष्टि हो गई!',
    'book.confirmed_subtitle': 'आपका सेवा अनुरोध पेशेवर को भेज दिया गया है।',
    'book.go_to_dashboard': 'डैशबोर्ड पर जाएं →',
    'book.back_to_home': 'होम पर वापस जाएं',

    // Worker Profile Page
    'wp.govt_verified': 'सरकारी आईडी सत्यापित',
    'wp.specialist': 'विशेषज्ञ',
    'wp.serving': 'सेवा क्षेत्र',
    'wp.per_hour': 'प्रति घंटा',
    'wp.public_preview': 'सार्वजनिक पूर्वावलोकन',
    'wp.how_others_view': 'दूसरे आपकी प्रोफ़ाइल ऐसे देखते हैं।',
    'wp.edit_profile': 'प्रोफ़ाइल संपादित करें →',
    'wp.book_now': '{name} को अभी बुक करें →',
    'wp.perf_highlights': 'प्रदर्शन मुख्य बातें',
    'wp.rating': 'रेटिंग',
    'wp.reviews': 'समीक्षाएं',
    'wp.experience': 'अनुभव',
    'wp.radius': 'दायरा',
    'wp.about': '{name} के बारे में',
    'wp.services_offered': 'विशेष सेवाएं ({count})',
    'wp.trust_verification': 'विश्वास और सत्यापन',
    'wp.bg_checked': 'पृष्ठभूमि जाँची गई',
    'wp.fast_dispatch': 'त्वरित प्रेषण (<30 मिनट)',
    'wp.working_hours': 'सोम-शनि (सुबह 8 - शाम 8)',
    'wp.no_hidden_fees': 'कोई छिपा शुल्क नहीं',
    'wp.guarantee_title': 'FixItNow सेवा गारंटी',
    'wp.guarantee_desc': 'प्रत्येक बुकिंग सुरक्षित है। यदि 7 दिनों में समस्या फिर आती है तो हम मुफ़्त पुनः भेंट की व्यवस्था करते हैं।',
    'wp.customer_reviews': 'ग्राहक समीक्षाएं ({count})',
    'wp.no_reviews': 'अभी कोई समीक्षा नहीं।',
    'wp.worker_not_found': 'कामगार नहीं मिला।',
    'wp.browse_workers': 'कामगार खोजें',
    'wp.yrs': 'वर्ष',
    'wp.km': 'किमी',

    // Profile Settings Page
    'profile.account_preferences': 'खाता प्राथमिकताएं',
    'profile.edit_profile': 'प्रोफ़ाइल संपादित करें',
    'profile.manage_subtitle': 'अपनी व्यक्तिगत सेटिंग्स, स्थान जानकारी और पेशेवर सेवा प्राथमिकताओं को प्रबंधित करें।',
    'profile.loading': 'प्रोफ़ाइल सेटिंग्स लोड हो रही हैं...',
    'profile.upload_photo': 'फोटो अपलोड करें',
    'profile.hide_url': 'URL इनपुट छुपाएं',
    'profile.paste_url': 'या इमेज URL पेस्ट करें',
    'profile.service_provider': 'सेवा प्रदाता',
    'profile.customer_account': 'ग्राहक खाता',
    'profile.member_since': 'सदस्य बने',
    'profile.gps_location': 'GPS स्थान',
    'profile.mapped': 'मैप किया गया',
    'profile.unmapped': 'मैप नहीं किया',
    'profile.selected_trade': 'चयनित व्यवसाय',
    'profile.hourly_rate': 'प्रति घंटा दर',
    'profile.service_radius': 'सेवा त्रिज्या',
    'profile.availability': 'उपलब्धता',
    'profile.online': 'ऑनलाइन',
    'profile.offline': 'ऑफ़लाइन',
    'profile.personal_details': 'व्यक्तिगत विवरण',
    'profile.location_area': 'स्थान और क्षेत्र',
    'profile.service_profile': 'सेवा प्रोफ़ाइल',
    'profile.account_details': 'खाता विवरण',
    'profile.account_details_desc': 'अपनी पहचान और फोन संपर्क जानकारी अपडेट करें।',
    'profile.full_name': 'पूरा नाम',
    'profile.full_name_placeholder': 'अपना पूरा नाम दर्ज करें',
    'profile.phone_number': 'फोन नंबर',
    'profile.location_title': 'स्थान पता और सेवा शहर',
    'profile.location_desc': 'दूरी फिल्टर की गणना करने और आसपास के ग्राहकों को आपकी प्रोफ़ाइल दिखाने के लिए उपयोग किया जाता है।',
    'profile.city_label': 'शहर / संचालन क्षेत्र',
    'profile.city_placeholder': 'उदा. मुंबई, दिल्ली, बेंगलुरु',
    'profile.mapping_gps': 'GPS मैपिंग...',
    'profile.auto_detect_gps': 'GPS निर्देशांक स्वतः पता लगाएं',
    'profile.service_settings_title': 'पेशेवर सेवा प्रोफ़ाइल सेटिंग्स',
    'profile.service_settings_desc': 'ग्राहकों को दिखाई गई व्यापार विशेषता, प्रति घंटा दर, और सेवा त्रिज्या कॉन्फ़िगर करें।',
    'profile.select_trade': 'व्यापार विशेषता चुनें',
    'profile.hourly_rate_label': 'प्रति घंटा दर (₹/घंटा)',
    'profile.experience_label': 'अनुभव (वर्ष)',
    'profile.radius_label': 'सेवा क्षेत्र त्रिज्या (किमी)',
    'profile.availability_status': 'उपलब्धता स्थिति',
    'profile.availability_desc': 'नियंत्रित करता है कि आपकी प्रोफ़ाइल सक्रिय खोज परिणामों में सूचीबद्ध है या नहीं',
    'profile.bio_label': 'पेशेवर परिचय',
    'profile.bio_placeholder': 'अपनी सेवा विशेषज्ञता, मरम्मत गारंटी, और योग्यताओं का वर्णन करें...',
    'profile.services_offered': 'अनुकूलित सेवाएं',
    'profile.services_offered_desc': 'चुनें कि आप अपने क्षेत्र के गृहस्वामियों को कौन सी विशेष मरम्मत सेवाएं प्रदान करते हैं।',
    'profile.additional_custom': 'अतिरिक्त कस्टम सेवाएं:',
    'profile.add_custom_placeholder': 'कस्टम सेवा जोड़ें (उदा. स्मार्ट लॉक इंस्टॉलेशन)...',
    'profile.add_service': '+ सेवा जोड़ें',
    'profile.saving': 'सेटिंग्स सहेजी जा रही हैं...',
    'profile.save_cta': 'प्रोफ़ाइल और सेवा सेटिंग्स सहेजें →',
  },
  kn: {
    // Navbar
    'nav.home': 'ಮುಖಪುಟ',
    'nav.find_workers': 'ಕೆಲಸಗಾರರನ್ನು ಹುಡುಕಿ',
    'nav.upload_problem': 'ಸಮಸ್ಯೆಯನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    'nav.dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'nav.sign_in': 'ಸೈನ್ ಇನ್',
    'nav.get_started': 'ಪ್ರಾರಂಭಿಸಿ',
    'nav.sign_out': 'ಸೈನ್ ಔಟ್',
    'nav.profile_settings': 'ಪ್ರೊಫೈಲ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'nav.worker_dashboard': 'ಕೆಲಸಗಾರರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    
    // Auth / Onboarding
    'auth.welcome_back': 'ಮರಳಿ ಸುಸ್ವಾಗತ',
    'auth.sign_in_subtitle': 'ಮುಂದುವರಿಯಲು ನಿಮ್ಮ ಖಾತೆಗೆ ಸೈನ್ ಇನ್ ಮಾಡಿ',
    'auth.continue_google': 'Google ನೊಂದಿಗೆ ಮುಂದುವರಿಯಿರಿ',
    'auth.or_sign_in_email': 'ಅಥವಾ ಇಮೇಲ್ ಮೂಲಕ ಸೈನ್ ಇನ್ ಮಾಡಿ',
    'auth.email_label': 'ಇಮೇಲ್ ವಿಳಾಸ',
    'auth.password_label': 'ಪಾಸ್‌ವರ್ಡ್',
    'auth.sign_in_btn': 'ಸೈನ್ ಇನ್',
    'auth.signing_in': 'ಸೈನ್ ಇನ್ ಆಗುತ್ತಿದೆ...',
    'auth.no_account': 'ಖಾತೆ ಇಲ್ಲವೇ?',
    'auth.create_one_free': 'ಉಚಿತವಾಗಿ ರಚಿಸಿ',
    'auth.already_account': 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?',
    'auth.sign_in': 'ಸೈನ್ ಇನ್ ಮಾಡಿ',
    'auth.get_started_hub': 'ಪ್ರಾರಂಭ ಕೇಂದ್ರ',
    'auth.join_title': 'FixItNow ಸೇರಿ',
    'auth.join_subtitle': 'ತ್ವರಿತ AI ಹಾನಿ ತಪಾಸಣೆ ಮತ್ತು ಸ್ಥಳೀಯ ವೃತ್ತಿಪರ ಬುಕಿಂಗ್‌ನೊಂದಿಗೆ ಪ್ರಾರಂಭಿಸಲು ವೇದಿಕೆಯನ್ನು ಹೇಗೆ ಬಳಸಬೇಕೆಂದು ಆಯ್ಕೆಮಾಡಿ',
    'auth.homeowners_badge': 'ಮನೆಮಾಲೀಕರು',
    'auth.homeowner_title': 'ನನಗೆ ದುರಸ್ತಿ / ಸಹಾಯ ಬೇಕು',
    'auth.homeowner_desc': 'ಗೃಹ ಸಮಸ್ಯೆಯನ್ನು ಪೋಸ್ಟ್ ಮಾಡಿ, ಫೋಟೋ/ವೀಡಿಯೊ ತೆಗೆಯಿರಿ, ತಕ್ಷಣದ AI ವಿಶ್ಲೇಷಣೆ ಪಡೆಯಿರಿ ಮತ್ತು ಪರಿಶೀಲಿಸಿದ ವೃತ್ತಿಪರರನ್ನು ನೇಮಿಸಿ.',
    'auth.homeowner_feature_1': 'AI ಸಮಸ್ಯೆ ಪತ್ತೆ ಮತ್ತು ವೆಚ್ಚದ ಅಂದಾಜು',
    'auth.homeowner_feature_2': 'ಜಿಪಿಎಸ್ ವೃತ್ತಿಪರ ದೂರ ಹೊಂದಾಣಿಕೆ (<30 ನಿಮಿಷ)',
    'auth.homeowner_feature_3': 'ತ್ವರಿತ ಬುಕಿಂಗ್ ಲಭ್ಯತೆ',
    'auth.homeowner_cta': 'ಮನೆಮಾಲೀಕರಾಗಿ ಸೈನ್ ಅಪ್ ಮಾಡಿ →',
    'auth.pro_badge': 'ವೃತ್ತಿಪರರಿಗೆ',
    'auth.worker_title': 'ನಾನ್ ಒಬ್ಬ ಕೆಲಸಗಾರ / ಸೇವಾದಾತ',
    'auth.worker_desc': 'ನಿಮ್ಮ ಸೇವೆಗಳನ್ನು ಪಟ್ಟಿ ಮಾಡಿ, ದರಗಳನ್ನು ನಿಗದಿಪಡಿಸಿ ಮತ್ತು ಹತ್ತಿರದ ಕೆಲಸಗಳನ್ನು ಸ್ವೀಕರಿಸಿ.',
    'auth.worker_feature_1': 'ವಿಶೇಷ ವೃತ್ತಿ ಪಟ್ಟಿ',
    'auth.worker_feature_2': 'ನಿಮ್ಮ ದರಗಳು ಮತ್ತು ಹೊಂದಿಕೊಳ್ಳುವ ಸಮಯ ನಿಗದಿಪಡಿಸಿ',
    'auth.worker_feature_3': 'ನೇರ ಗ್ರಾಹಕ ಕೆಲಸದ ಬುಕಿಂಗ್‌ಗಳನ್ನು ಸ್ವೀಕರಿಸಿ',
    'auth.worker_cta': 'ಸೇವಾ ವೃತ್ತಿಪರರಾಗಿ ಸೈನ್ ಅಪ್ ಮಾಡಿ →',
    'auth.trust_dispatch': 'ಸರಾಸರಿ 15 ನಿಮಿಷಗಳಲ್ಲಿ ನಿಯೋಜನೆ',
    'auth.trust_verified': '100% ಪರಿಶೀಲಿಸಿದ ವೃತ್ತಿಪರರು',
    'auth.trust_ai': 'AI ವಿಷನ್ ಶಕ್ತಿ ಹೊಂದಿದ',
    'auth.homeowner': 'ನನಗೆ ದುರಸ್ತಿ / ಸಹಾಯ ಬೇಕು',
    'auth.worker': 'ನಾನು ಒಬ್ಬ ಕೆಲಸಗಾರ / ಸೇವಾ ಪೂರೈಕೆದಾರ',
    'auth.homeowner_client': 'ಮನೆಮಾಲೀಕ / ಗ್ರಾಹಕ',
    'auth.service_pro_worker': 'ಸೇವಾ ವೃತ್ತಿಪರ / ಕೆಲಸಗಾರ',
    'auth.register_as_customer': 'ಗ್ರಾಹಕರಾಗಿ ನೋಂದಾಯಿಸಿ',
    'auth.customer_subtitle': 'ತಕ್ಷಣದ AI ಹಾನಿ ತಪಾಸಣೆ ಪಡೆಯಿರಿ ಮತ್ತು ಸ್ಥಳೀಯ ದುರಸ್ತಿ ವೃತ್ತಿಪರರನ್ನು ನೇಮಿಸಿ',
    'auth.register_as_worker': 'ಕೆಲಸಗಾರರಾಗಿ ನೋಂದಾಯಿಸಿ',
    'auth.worker_subtitle': 'ನಿಮ್ಮ ವೈಶಿಷ್ಟ್ಯಗಳನ್ನು ಪಟ್ಟಿ ಮಾಡಿ, ದರವನ್ನು ನಿಗದಿಪಡಿಸಿ ಮತ್ತು ಸ್ಥಳೀಯ ಕೆಲಸಗಳನ್ನು ಪಡೆಯಲು ಪ್ರಾರಂಭಿಸಿ',
    'auth.sign_up_google': 'Google ನೊಂದಿಗೆ ಸೈನ್ ಅಪ್ ಮಾಡಿ',
    'auth.or_register_email': 'ಅಥವಾ ಇಮೇಲ್ ಮೂಲಕ ನೋಂದಾಯಿಸಿ',
    'auth.full_name': 'ಪೂರ್ಣ ಹೆಸರು',
    'auth.phone_number': 'ಫೋನ್ ಸಂಖ್ಯೆ',
    'auth.email_address': 'ಇಮೇಲ್ ವಿಳಾಸ',
    'auth.password': 'ಪಾಸ್‌ವರ್ಡ್',
    'auth.select_primary_trade': 'ನಿಮ್ಮ ಪ್ರಾಥಮಿಕ ವೃತ್ತಿಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    'auth.select_trade_placeholder': 'ನಿಮ್ಮ ವೃತ್ತಿಯ ವಿಶೇಷತೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ...',
    'auth.specify_trade_label': 'ನಿಮ್ಮ ಕೆಲಸ / ವೃತ್ತಿಯನ್ನು ನಿರ್ದಿಷ್ಟಪಡಿಸಿ (ಪಟ್ಟಿ ಮಾಡಲಾಗಿಲ್ಲ)',
    'auth.create_customer_account': 'ಗ್ರಾಹಕ ಖಾತೆಯನ್ನು ರಚಿಸಿ →',
    'auth.create_worker_account': 'ಕೆಲಸಗಾರ ಖಾತೆಯನ್ನು ರಚಿಸಿ →',
    'auth.connecting_google': 'Google ನೊಂದಿಗೆ ಸಂಪರ್ಕಿಸಲಾಗುತ್ತಿದೆ...',
    'auth.creating_account': 'ಖಾತೆಯನ್ನು ರಚಿಸಲಾಗುತ್ತಿದೆ...',
    
    // Sidebar Dock
    'dock.worker_console': 'ಕೆಲಸಗಾರರ ಕಾನ್ಸೋಲ್',
    'dock.incoming_requests': 'ಬರುವ ವಿನಂತಿಗಳು',
    'dock.active_jobs': 'ಸಕ್ರಿಯ ಕೆಲಸಗಳು',
    'dock.completed_history': 'ಪೂರ್ಣಗೊಂಡ ಇತಿಹಾಸ',
    'dock.location_radius': 'ಸ್ಥಳ ಮತ್ತು ತ್ರಿಜ್ಯ',
    'dock.trade_settings': 'ಸೇವಾ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'dock.account_settings': 'ಖಾತೆ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'dock.my_dashboard': 'ನನ್ನ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'dock.browse_workers': 'ಕೆಲಸಗಾರರನ್ನು ಹುಡುಕಿ',
    'dock.ai_scanner': 'AI ಸಮಸ್ಯೆಯ ಸ್ಕ್ಯಾನರ್',
    'dock.home_page': 'ಮುಖಪುಟ',
    'dock.find_workers': 'ಕೆಲಸಗಾರರನ್ನು ಹುಡುಕಿ',
    'dock.sign_in_register': 'ಸೈನ್ ಇನ್ / ನೋಂದಣಿ',
    'dock.console': 'ಕಾನ್ಸೋಲ್',
    'dock.main_menu': 'ಮುಖ್ಯ ಮೆನು',

    // Dashboard
    'dashboard.welcome': 'ಮರಳಿ ಸ್ವಾಗತ, {name}!',
    'dashboard.manage_requests': 'ನಿಮ್ಮ ಸೇವಾ ವಿನಂತಿಗಳು, ಬುಕಿಂಗ್‌ಗಳು ಮತ್ತು ಸಕ್ರಿಯ ರಿಪೇರಿಗಳನ್ನು ನಿರ್ವಹಿಸಿ.',
    'dashboard.file_new_problem': 'ಹೊಸ ಸಮಸ್ಯೆಯನ್ನು ಫೈಲ್ ಮಾಡಿ',
    'dashboard.total_issues': 'ಒಟ್ಟು ಸಮಸ್ಯೆಗಳು',
    'dashboard.active_repairs': 'ಸಕ್ರಿಯ ರಿಪೇರಿಗಳು',
    'dashboard.bookings': 'ಬುಕಿಂಗ್‌ಗಳು',
    'dashboard.no_issues': 'ಇನ್ನೂ ಯಾವುದೇ ಸಮಸ್ಯೆಗಳನ್ನು ಪೋಸ್ಟ್ ಮಾಡಲಾಗಿಲ್ಲ',
    'dashboard.upload_photo': 'ಪ್ರಾರಂಭಿಸಲು ನಿಮ್ಮ ಸಮಸ್ಯೆಯ ಫೋಟೋವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.',
    'dashboard.file_problem': 'ಈಗಲೇ ಸಮಸ್ಯೆಯನ್ನು ಫೈಲ್ ಮಾಡಿ',
    'dashboard.no_bookings': 'ಇನ್ನೂ ಯಾವುದೇ ಬುಕಿಂಗ್‌ಗಳಿಲ್ಲ',
    'dashboard.book_worker': 'ನಿಮ್ಮ ಬುಕಿಂಗ್‌ಗಳನ್ನು ಇಲ್ಲಿ ವೀಕ್ಷಿಸಲು ಕೆಲಸಗಾರರನ್ನು ಬುಕ್ ಮಾಡಿ.',
    'dashboard.posted_issues': 'ನನ್ನ ಪೋಸ್ಟ್ ಮಾಡಲಾದ ಸಮಸ್ಯೆಗಳು',
    'dashboard.booking_requests': 'ಬುಕಿಂಗ್ ವಿನಂತಿಗಳು',

    // Trades
    'trade.plumber': 'ಪ್ಲಂಬರ್ (Plumber)',
    'trade.electrician': 'ಎಲೆಕ್ಟ್ರಿಷಿಯನ್ (Electrician)',
    'trade.carpenter': 'ಕಾರ್ಪೆಂಟರ್ (Carpenter)',
    'trade.painter': 'ಪೇಂಟರ್ (Painter)',
    'trade.ac_tech': 'ಎಸಿ ತಂತ್ರಜ್ಞ (AC Tech)',
    'trade.welder': 'ವೆಲ್ಡರ್ (Welder)',
    'trade.mason': 'ಮೇಸ್ತ್ರಿ (Mason)',
    'trade.other': 'ಸಾಮಾನ್ಯ ಕೆಲಸಗಾರ',

    // Workers page
    'workers.service_directory': 'ಸೇವಾ ಡೈರೆಕ್ಟರಿ',
    'workers.find_verified_workers': 'ಪರಿಶೀಲಿಸಿದ ಕೆಲಸಗಾರರನ್ನು ಹುಡುಕಿ',
    'workers.browse_subtitle': 'ನಿಮ್ಮ ಸ್ಥಳೀಯ ಪ್ರದೇಶದಲ್ಲಿ ನುರಿತ ವೃತ್ತಿಪರರನ್ನು ಹುಡುಕಿ ಮತ್ತು ಬುಕ್ ಮಾಡಿ.',
    'workers.all_trades': 'ಎಲ್ಲಾ ವಿಭಾಗಗಳು',
    'workers.search_placeholder': 'ಕೆಲಸಗಾರನ ಹೆಸರು ಅಥವಾ ನಗರವನ್ನು ಹುಡುಕಿ...',
    'workers.sort_by': 'ವರ್ಗೀಕರಿಸಿ',
    'workers.online_available': 'ಆನ್‌ಲೈನ್ ಮತ್ತು ಲಭ್ಯವಿದೆ',
    'workers.finding_workers': 'ಕೆಲಸಗಾರರನ್ನು ಹುಡುಕಲಾಗುತ್ತಿದೆ...',
    'workers.no_matching_workers': 'ನಿಮ್ಮ ಫಿಲ್ಟರ್‌ಗಳಿಗೆ ಯಾವುದೇ ಕೆಲಸಗಾರರು ಹೊಂದಿಕೆಯಾಗುತ್ತಿಲ್ಲ',
    'workers.clear_filters_hint': 'ನಿಮ್ಮ ಹುಡುಕಾಟವನ್ನು ತೆರವುಗೊಳಿಸಲು, ಆಫ್‌ಲೈನ್ ಕೆಲಸಗಾರರನ್ನು ಬದಲಾಯಿಸಲು ಅಥವಾ ಬೇರೆ ವಿಭಾಗವನ್ನು ಆಯ್ಕೆ ಮಾಡಲು ಪ್ರಯತ್ನಿಸಿ.',
    
    // Sort options
    'sort.distance': 'ದೂರ (ಹತ್ತಿರದ)',
    'sort.rating': 'ರೇಟಿಂಗ್ (ಹೆಚ್ಚಿನ)',
    'sort.price_asc': 'ಬೆಲೆ (ಕಡಿಮೆ ಮೊದಲು)',
    'sort.experience': 'ಅನುಭವ (ಹೆಚ್ಚಿನ)',

    // WorkerCard
    'card.verified': 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
    'card.reviews': 'ವಿಮರ್ಶೆಗಳು',
    'card.experience': 'ಅನುಭವ',
    'card.away': 'ದೂರ',
    'card.view_profile': 'ಪ್ರೊಫೈಲ್ ವೀಕ್ಷಿಸಿ',
    'card.book_now': 'ಈಗಲೇ ಬುಕ್ ಮಾಡಿ',

    // Home landing page
    'home.hero_title': 'ನಿಮ್ಮ ಮನೆಯ ಸಮಸ್ಯೆ, ನಿಮಿಷಗಳಲ್ಲಿ ಪರಿಹರಿಸಲಾಗಿದೆ.',
    'home.hero_subtitle': 'ಫೋಟೋ ಅಥವಾ ವೀಡಿಯೊವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ. ನಮ್ಮ AI ಸಮಸ್ಯೆಯನ್ನು ಗುರುತಿಸುತ್ತದೆ ಮತ್ತು ನಿಮ್ಮ ಹತ್ತಿರದ ಪರಿಶೀಲಿಸಿದ ಕೆಲಸಗಾರರೊಂದಿಗೆ ತಕ್ಷಣ ನಿಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸುತ್ತದೆ.',
    'home.upload_problem': 'ಸಮಸ್ಯೆಯನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    'home.services_tag': 'ಸೇವೆಗಳು',
    'home.services_title': 'ಪ್ರತಿಯೊಂದು ವಿಭಾಗ, ಒಂದೇ ವೇದಿಕೆ',
    'home.services_subtitle': 'ಪ್ಲಂಬಿಂಗ್‌ನಿಂದ ಪೇಂಟಿಂಗ್‌ನವರೆಗೆ — ನಿಮ್ಮ ಎಲ್ಲಾ ಮನೆ ಸೇವೆಗಳ ಅಗತ್ಯತೆಗಳನ್ನು ಪೂರೈಸಲಾಗುತ್ತದೆ.',
    'home.how_it_works_tag': 'ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ',
    'home.how_it_works_title': '3 ಸರಳ ಹಂತಗಳಲ್ಲಿ ಪರಿಹರಿಸಿ',
    'home.step1_title': 'ಫೋಟೋ ಅಥವಾ ವೀಡಿಯೊ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    'home.step1_desc': 'ಸಮಸ್ಯೆಯ ಫೋಟೋ ಅಥವಾ ಸಣ್ಣ ವೀಡಿಯೊ ತೆಗೆದುಕೊಳ್ಳಿ — ಪೈಪ್ ಬಿರುಕು, ಮುರಿದ ಸಾಕೆಟ್, ಇನ್ನಿತರ ಯಾವುದೇ ಸಮಸ್ಯೆ.',
    'home.step2_title': 'AI ಸಮಸ್ಯೆಯನ್ನು ಗುರುತಿಸುತ್ತದೆ',
    'home.step2_desc': 'ನಮ್ಮ AI ಎಂಜಿನ್ ಸಮಸ್ಯೆಯನ್ನು ಗುರುತಿಸುತ್ತದೆ, ಹಾನಿಯ ಗಾತ್ರವನ್ನು ಅಂದಾಜು ಮಾಡುತ್ತದೆ ಮತ್ತು ಅಗತ್ಯವಿರುವ ವಿಭಾಗವನ್ನು ವರ್ಗೀಕರಿಸುತ್ತದೆ.',
    'home.step3_title': 'ಕೆಲಸಗಾರನನ್ನು ನಿಯೋಜಿಸಲಾಗುತ್ತದೆ',
    'home.step3_desc': 'ನಿಮ್ಮ ಹತ್ತಿರದ ಸರಿಯಾದ ವೃತ್ತಿಪರರನ್ನು ಹೊಂದಿಸಿ ಸೂಚಿಸಲಾಗುತ್ತದೆ. ಒಂದೇ ಟ್ಯಾಪ್‌ನಲ್ಲಿ ಬುಕ್ ಮಾಡಿ.',
    'home.try_it_free': 'ಈಗಲೇ ಪ್ರಯತ್ನಿಸಿ — ಇದು ಉಚಿತ →',
    'home.ai_powered_tag': 'AI-ಚಾಲಿತ',
    'home.ai_title': 'ಕೇವಲ ಡೈರೆಕ್ಟರಿ ಅಲ್ಲ. ಒಂದು ಸ್ಮಾರ್ಟ್ ಸಮಸ್ಯೆ ನಿವಾರಕ.',
    'home.ai_subtitle': 'ನಮ್ಮ AI ದೃಷ್ಟಿ ಮಾದರಿಯು ನಿಮ್ಮ ಫೋಟೋ ಅಥವಾ ವೀಡಿಯೊವನ್ನು ವಿಶ್ಲೇಷಿಸುತ್ತದೆ — ಸಮಸ್ಯೆಯ ಪ್ರಕಾರವನ್ನು ಪತ್ತೆಹಚ್ಚುತ್ತದೆ, ಆಯಾಮಗಳನ್ನು ಅಂದಾಜು ಮಾಡುತ್ತದೆ, ತೀವ್ರತೆಯನ್ನು ನಿರ್ಣಯಿಸುತ್ತದೆ ಮತ್ತು ಸರಿಯಾದ ವೃತ್ತಿಪರ ಕೆಲಸಗಾರನನ್ನು ಆಯ್ಕೆ ಮಾಡುತ್ತದೆ.',
    'home.upload_cta': 'ನಿಮ್ಮ ಸಮಸ್ಯೆಯನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ →',
    'home.final_title': 'ಮನೆಯಲ್ಲಿ ಯಾವುದೇ ಸಮಸ್ಯೆ ಇದೆಯೇ?',
    'home.final_subtitle': 'ಈಗಲೇ ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ. ಬಾಕಿ ಕೆಲಸವನ್ನು AI ನೋಡಿಕೊಳ್ಳುತ್ತದೆ.',
    'home.upload_free': 'ಸಮಸ್ಯೆ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ — ಉಚಿತ',
    'home.detecting_location': 'ಸ್ಥಳ ಪತ್ತೆಹಚ್ಚಲಾಗುತ್ತಿದೆ...',
    'home.stat_jobs_completed': 'ಪೂರ್ಣಗೊಂಡ ಕೆಲಸಗಳು',
    'home.stat_verified_workers': 'ಪರಿಶೀಲಿಸಿದ ಕೆಲಸಗಾರರು',
    'home.stat_satisfaction_rate': 'ತೃಪ್ತಿ ದರ',
    'home.stat_avg__response_time': 'ಸರಾಸರಿ ಪ್ರತಿಕ್ರಿಯೆ ಸಮಯ',

    // AI Demo details
    'demo.pipe_detected': 'ಸೋರುತ್ತಿರುವ ಪಿವಿಸಿ ಪೈಪ್ ಪತ್ತೆಯಾಗಿದೆ',
    'demo.urgent': '🔴 ತುರ್ತು',
    'demo.plumbers_available': '2 ಕಿಮೀ ವ್ಯಾಪ್ತಿಯಲ್ಲಿ 3 ಪ್ಲಂಬರ್‌ಗಳು ಲಭ್ಯವಿದ್ದಾರೆ',
    'demo.required': 'ಅಗತ್ಯವಿದೆ',
    'demo.problem_lbl': 'ಸಮಸ್ಯೆ:',
    'demo.problem_val': 'ಬಿರುಕು ಬಿಟ್ಟ ಪಿವಿಸಿ ನೀರಿನ ಪೈಪ್',
    'demo.dimension_lbl': 'ಆಯಾಮ:',
    'demo.dimension_val': '~25 ಸೆಂಮೀ ಬಿರುಕು',
    'demo.severity_lbl': 'ತೀವ್ರತೆ:',
    'demo.confidence_lbl': 'ಆತ್ಮವಿಶ್ವಾಸ:',
    'demo.reviews_tag': 'ವಿಮರ್ಶೆಗಳು',
    'demo.reviews_title': 'ಮನೆಮಾಲೀಕರಿಂದ ಮೆಚ್ಚುಗೆ ಪಡೆದಿದೆ',
    'home.ai_feature_1': '50+ ಕ್ಕೂ ಹೆಚ್ಚು ಮನೆಯ ಸಮಸ್ಯೆಗಳನ್ನು ಗುರುತಿಸುತ್ತದೆ',
    'home.ai_feature_2': 'ಹಾನಿಯ ಗಾತ್ರ/ಉದ್ದ/ವಿಸ್ತೀರ್ಣವನ್ನು ಅಂದಾಜು ಮಾಡುತ್ತದೆ',
    'home.ai_feature_3': 'ತುರ್ತು ಮಟ್ಟವನ್ನು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ವರ್ಗೀಕರಿಸುತ್ತದೆ',
    'home.ai_feature_4': 'ಹತ್ತಿರದ ಪರಿಶೀಲಿಸಿದ ವೃತ್ತಿಪರರೊಂದಿಗೆ ಹೊಂದಿಸುತ್ತದೆ',

    // Upload page
    'upload.detect_problem': 'ಸಮಸ್ಯೆ ಪತ್ತೆಹಚ್ಚಿ',
    'upload.whats_problem': 'ಸಮಸ್ಯೆ ಏನು?',
    'upload.subtitle': 'ಸಮಸ್ಯೆಯ ಫೋಟೋ ಅಥವಾ ವೀಡಿಯೊವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ. ನಮ್ಮ AI ಸಮಸ್ಯೆಯನ್ನು ಪತ್ತೆಹಚ್ಚುತ್ತದೆ ಮತ್ತು ಸರಿಯಾದ ಕೆಲಸಗಾರನನ್ನು ಹುಡುಕುತ್ತದೆ.',
    'upload.photo_tab': 'ಫೋಟೋ',
    'upload.video_tab': 'ವೀಡಿಯೊ',
    'upload.drag_photo': 'ಸಮಸ್ಯೆಯ ಫೋಟೋವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    'upload.drag_video': 'ಸಮಸ್ಯೆಯ ವೀಡಿಯೊವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    'upload.choose_photo': 'ಫೋಟೋ ಆಯ್ಕೆಮಾಡಿ',
    'upload.take_photo': 'ಫೋಟೋ ತೆಗೆದುಕೊಳ್ಳಿ',
    'upload.choose_video': 'ವೀಡಿಯೊ ಆಯ್ಕೆಮಾಡಿ',
    'upload.record_video': 'ವೀಡಿಯೊ ರೆಕಾರ್ಡ್ ಮಾಡಿ',
    'upload.drag_drop_hint': 'ಎಳೆದು ಬಿಡಿ ಅಥವಾ ಹುಡುಕಲು ಕ್ಲಿಕ್ ಮಾಡಿ — ಗರಿಷ್ಠ 20MB',
    'upload.tip_video_lighting': 'ವೀಡಿಯೊದುದ್ದಕ್ಕೂ ಉತ್ತಮ ಬೆಳಕನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ',
    'upload.tip_video_duration': 'ವೀಡಿಯೊವನ್ನು 30 ಸೆಕೆಂಡ್‌ಗಿಂತ ಕಡಿಮೆ ಇರಿಸಿ',
    'upload.tip_video_focus': 'ಹಾನಿಗೊಳಗಾದ ಪ್ರದೇಶದ ಮೇಲೆ ಕೇಂದ್ರೀಕರಿಸಿ',
    'upload.tip_video_angles': 'ಸಮಸ್ಯೆಯನ್ನು ವಿವಿಧ ಕೋನಗಳಿಂದ ತೋರಿಸಿ',
    'upload.tip_video_steady': 'ಫೋನ್ ಅನ್ನು ಸ್ಥಿರವಾಗಿ ಹಿಡಿದುಕೊಳ್ಳಿ, ಅಲುಗಾಡಿಸಬೇಡಿ',
    'upload.tip_video_scale': 'ಅಳತೆಗಾಗಿ ಒಂದು ಉಲ್ಲೇಖ ವಸ್ತುವನ್ನು ಸೇರಿಸಿ',
    'upload.tip_image_lighting': 'ಉತ್ತಮ ಬೆಳಕನ್ನು ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ',
    'upload.tip_image_scale': 'ಅಳತೆಗಾಗಿ ಏನನ್ನಾದರೂ ಸೇರಿಸಿ (ಅಳತೆಗೋಲು, ನಾಣ್ಯ)',
    'upload.tip_image_focus': 'ಹಾನಿಗೊಳಗಾದ ಪ್ರದೇಶದ ಮೇಲೆ ಕೇಂದ್ರೀಕರಿಸಿ',
    'upload.tip_image_angles': 'ಸಾಧ್ಯವಾದರೆ ವಿವಿಧ ಕೋನಗಳಿಂದ ಫೋಟೋ ತೆಗೆದುಕೊಳ್ಳಿ',
    'upload.location_unavailable': 'ಸ್ಥಳ ಲಭ್ಯವಿಲ್ಲ — ಕೆಲಸಗಾರರ ಹುಡುಕಾಟ ಕಡಿಮೆ ನಿಖರವಾಗಿರಬಹುದು',
    'upload.remove': 'ತೆಗೆದುಹಾಕಿ',
    'upload.analyzing_video': 'ವೀಡಿಯೊವನ್ನು ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...',
    'upload.analyzing_photo': 'ಫೋಟೋವನ್ನು ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...',
    'upload.analyze_video_cta': '🤖 AI ನೊಂದಿಗೆ ವೀಡಿಯೊವನ್ನು ವಿಶ್ಲೇಷಿಸಿ →',
    'upload.analyze_photo_cta': '🤖 AI ನೊಂದಿಗೆ ಫೋಟೋವನ್ನು ವಿಶ್ಲೇಷಿಸಿ →',
    'upload.video_note': '💡 ಸಮಸ್ಯೆಯನ್ನು ಪತ್ತೆಹಚ್ಚಲು, ಆಯಾಮಗಳನ್ನು ಅಂದಾಜು ಮಾಡಲು ಮತ್ತು ತುರ್ತುಸ್ಥಿತಿಯನ್ನು ನಿರ್ಣಯಿಸಲು AI ಇಡೀ ವೀಡಿಯೊವನ್ನು ವೀಕ್ಷಿಸುತ್ತದೆ.',
    'upload.tips_title': 'ಉತ್ತಮ ಫಲಿತಾಂಶಗಳಿಗಾಗಿ ಸಲಹೆಗಳು',

    // Booking Page
    'book.tag': 'ಕೆಲಸಗಾರನನ್ನು ಬುಕ್ ಮಾಡಿ',
    'book.title': 'ನಿಮ್ಮ ಬುಕಿಂಗ್ ಅನ್ನು ದೃಢೀಕರಿಸಿ',
    'book.subtitle': 'ವೃತ್ತಿಪರ ವಿವರಗಳನ್ನು ಪರಿಶೀಲಿಸಿ ಮತ್ತು ಭೇಟಿಯ ಸಮಯವನ್ನು ಆಯ್ಕೆಮಾಡಿ.',
    'book.step1_header': 'ಭೇಟಿಯ ಸಮಯ ನಿಗದಿಪಡಿಸಿ',
    'book.step2_header': 'ಸ್ಥಳ ಮತ್ತು ಪಾವತಿ',
    'book.step_badge': 'ಹಂತ {step} / 2',
    'book.hourly_rate': 'ಗಂಟೆಯ ದರ',
    'book.experience': 'ಅನುಭವ',
    'book.locality': 'ಸ್ಥಳ',
    'book.reviews': 'ವಿಮರ್ಶೆಗಳು',
    'book.service_summary': 'ಸೇವೆಯ ಸಾರಾಂಶ',
    'book.verified_background': 'ಪರಿಶೀಲಿಸಿದ ಹಿನ್ನೆಲೆ',
    'book.fair_price_guarantee': 'ನ್ಯಾಯಯುತ ಬೆಲೆ ಭರವಸೆ',
    'book.visit_date': 'ಭೇಟಿಯ ದಿನಾಂಕ',
    'book.preferred_time': 'ಆದ್ಯತೆಯ ಸಮಯ',
    'book.describe_issue': 'ಸಮಸ್ಯೆಯನ್ನು ವಿವರಿಸಿ',
    'book.optional': 'ಐಚ್ಛಿಕ',
    'book.issue_placeholder': 'ಏನನ್ನು ಸರಿಪಡಿಸಬೇಕು ಅಥವಾ ಕೆಲಸಗಾರನಿಗೆ ಸೂಚನೆಗಳನ್ನು ಸಂಕ್ಷಿಪ್ತವಾಗಿ ಬರೆಯಿರಿ...',
    'book.booking_fee': 'ಬುಕಿಂಗ್ ಶುಲ್ಕ',
    'book.free': 'ಉಚಿತ (₹0)',
    'book.est_rate': 'ಅಂದಾಜು ದರ',
    'book.sign_in_continue': 'ಮುಂದುವರಿಯಲು ಸೈನ್ ಇನ್ ಮಾಡಿ →',
    'book.next_step': 'ಮುಂದೆ: ಸ್ಥಳ ಮತ್ತು ಪಾವತಿ →',
    'book.service_address': 'ಸೇವೆಯ ವಿಳಾಸ',
    'book.detect_gps': 'ಜಿಪಿಎಸ್ ಸ್ಥಳ ಗುರುತಿಸಿ',
    'book.address_placeholder': 'ಮನೆ/ಫ್ಲಾಟ್ ಸಂಖ್ಯೆ, ಬೀದಿ, ಲ್ಯಾಂಡ್‌ಮಾರ್ಕ್...',
    'book.pincode_city': 'ಪಿನ್‌ಕೋಡ್ / ನಗರ',
    'book.pincode_placeholder': 'ಉದಾ. 560001, ಬೆಂಗಳೂರು',
    'book.payment_method': 'ಪಾವತಿ ವಿಧಾನವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    'book.cash_payment': 'ನಗದು / ಕೆಲಸದ ನಂತರ ಪಾವತಿಸಿ',
    'book.cash_desc': 'ಇಂದು ಮುಂಗಡ ಪಾವತಿಯ ಅಗತ್ಯವಿಲ್ಲ',
    'book.upi_payment': 'ಯುಪಿಐ / ಜಿಪೇ / ಫೋನ್ ಪೇ',
    'book.upi_desc': 'ತ್ವರಿತ ಡಿಜಿಟಲ್ ಪಾವತಿ ಲಿಂಕ್',
    'book.card_payment': 'ಕ್ರೆಡಿಟ್ / ಡೆಬಿಟ್ ಕಾರ್ಡ್',
    'book.card_desc': 'ವಿಸಾ, ಮಾಸ್ಟರ್‌ಕಾರ್ಡ್, ರೂಪೇ',
    'book.back': '← ಹಿಂತಿರುಗಿ',
    'book.confirm_cta': 'ದೃಢೀಕರಿಸಿ ಮತ್ತು ಕೆಲಸಗಾರನನ್ನು ಬುಕ್ ಮಾಡಿ →',
    'book.booking_in_progress': 'ಬುಕಿಂಗ್ ಆಗುತ್ತಿದೆ...',
    'book.cancellation_note': 'ಕೆಲಸಗಾರ ಸ್ವೀಕರಿಸುವ ಮೊದಲು ಉಚಿತ ರದ್ದತಿ. ಕೆಲಸ ಪ್ರಾರಂಭವಾಗುವವರೆಗೆ ಯಾವುದೇ ಶುಲ್ಕವಿಲ್ಲ.',
    'book.confirmed_title': 'ಬುಕಿಂಗ್ ದೃಢೀಕರಿಸಲಾಗಿದೆ!',
    'book.confirmed_subtitle': 'ನಿಮ್ಮ ಸೇವಾ ವಿನಂತಿಯನ್ನು ವೃತ್ತಿಪರರಿಗೆ ಕಳುಹಿಸಲಾಗಿದೆ.',
    'book.go_to_dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ಗೆ ಹೋಗಿ →',
    'book.back_to_home': 'ಮುಖಪುಟಕ್ಕೆ ಹಿಂತಿರುಗಿ',

    // Worker Profile Page
    'wp.govt_verified': 'ಸರ್ಕಾರಿ ಐಡಿ ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
    'wp.specialist': 'ತಜ್ಞ',
    'wp.serving': 'ಸೇವಾ ಪ್ರದೇಶ',
    'wp.per_hour': 'ಪ್ರತಿ ಗಂಟೆಗೆ',
    'wp.public_preview': 'ಸಾರ್ವಜನಿಕ ಪೂರ್ವಾವಲೋಕನ',
    'wp.how_others_view': 'ಇತರರು ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಅನ್ನು ಹೇಗೆ ನೋಡುತ್ತಾರೆ.',
    'wp.edit_profile': 'ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ →',
    'wp.book_now': '{name} ಅನ್ನು ಈಗ ಬುಕ್ ಮಾಡಿ →',
    'wp.perf_highlights': 'ಕಾರ್ಯಕ್ಷಮತೆ ಮುಖ್ಯಾಂಶಗಳು',
    'wp.rating': 'ರೇಟಿಂಗ್',
    'wp.reviews': 'ವಿಮರ್ಶೆಗಳು',
    'wp.experience': 'ಅನುಭವ',
    'wp.radius': 'ತ್ರಿಜ್ಯ',
    'wp.about': '{name} ಬಗ್ಗೆ',
    'wp.services_offered': 'ವಿಶೇಷ ಸೇವೆಗಳು ({count})',
    'wp.trust_verification': 'ವಿಶ್ವಾಸ ಮತ್ತು ಪರಿಶೀಲನೆ',
    'wp.bg_checked': 'ಹಿನ್ನೆಲೆ ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
    'wp.fast_dispatch': 'ತ್ವರಿತ ನಿಯೋಜನೆ (<30 ನಿಮಿಷ)',
    'wp.working_hours': 'ಸೋಮ-ಶನಿ (ಬೆಳಗ್ಗೆ 8 - ಸಂಜೆ 8)',
    'wp.no_hidden_fees': 'ಯಾವುದೇ ಗುಪ್ತ ಶುಲ್ಕವಿಲ್ಲ',
    'wp.guarantee_title': 'FixItNow ಸೇವಾ ಖಾತ್ರಿ',
    'wp.guarantee_desc': 'ಪ್ರತಿ ಬುಕಿಂಗ್ ಸಂರಕ್ಷಿಸಲ್ಪಟ್ಟಿದೆ. 7 ದಿನಗಳಲ್ಲಿ ಸಮಸ್ಯೆ ಮರುಕಳಿಸಿದರೆ ನಾವು ಉಚಿತ ಅನುಸರಣಾ ಭೇಟಿ ಏರ್ಪಡಿಸುತ್ತೇವೆ.',
    'wp.customer_reviews': 'ಗ್ರಾಹಕರ ವಿಮರ್ಶೆಗಳು ({count})',
    'wp.no_reviews': 'ಇನ್ನೂ ಯಾವುದೇ ವಿಮರ್ಶೆಗಳಿಲ್ಲ.',
    'wp.worker_not_found': 'ಕೆಲಸಗಾರ ಕಂಡುಬಂದಿಲ್ಲ.',
    'wp.browse_workers': 'ಕೆಲಸಗಾರರನ್ನು ಹುಡುಕಿ',
    'wp.yrs': 'ವರ್ಷ',
    'wp.km': 'ಕಿಮೀ',

    // Profile Settings Page
    'profile.account_preferences': 'ಖಾತೆ ಆದ್ಯತೆಗಳು',
    'profile.edit_profile': 'ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ',
    'profile.manage_subtitle': 'ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಸೆಟ್ಟಿಂಗ್‌ಗಳು, ಸ್ಥಳ ಮಾಹಿತಿ, ಮತ್ತು ವೃತ್ತಿಪರ ಸೇವಾ ಆದ್ಯತೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ.',
    'profile.loading': 'ಪ್ರೊಫೈಲ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳನ್ನು ಲೋಡ್ ಮಾಡಲಾಗುತ್ತಿದೆ...',
    'profile.upload_photo': 'ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    'profile.hide_url': 'URL ಇನ್‌ಪುಟ್ ಮರೆಮಾಡಿ',
    'profile.paste_url': 'ಅಥವಾ ಚಿತ್ರ URL ಅಂಟಿಸಿ',
    'profile.service_provider': 'ಸೇವಾ ಪೂರೈಕೆದಾರ',
    'profile.customer_account': 'ಗ್ರಾಹಕ ಖಾತೆ',
    'profile.member_since': 'ಸದಸ್ಯತ್ವ ಆರಂಭ',
    'profile.gps_location': 'GPS ಸ್ಥಳ',
    'profile.mapped': 'ಮ್ಯಾಪ್ ಆಗಿದೆ',
    'profile.unmapped': 'ಮ್ಯಾಪ್ ಆಗಿಲ್ಲ',
    'profile.selected_trade': 'ಆಯ್ಕೆಮಾಡಿದ ವೃತ್ತಿ',
    'profile.hourly_rate': 'ಗಂಟೆಯ ದರ',
    'profile.service_radius': 'ಸೇವಾ ತ್ರಿಜ್ಯ',
    'profile.availability': 'ಲಭ್ಯತೆ',
    'profile.online': 'ಆನ್‌ಲೈನ್',
    'profile.offline': 'ಆಫ್‌ಲೈನ್',
    'profile.personal_details': 'ವೈಯಕ್ತಿಕ ವಿವರಗಳು',
    'profile.location_area': 'ಸ್ಥಳ ಮತ್ತು ಪ್ರದೇಶ',
    'profile.service_profile': 'ಸೇವಾ ಪ್ರೊಫೈಲ್',
    'profile.account_details': 'ಖಾತೆ ವಿವರಗಳು',
    'profile.account_details_desc': 'ನಿಮ್ಮ ಗುರುತು ಮತ್ತು ಫೋನ್ ಸಂಪರ್ಕ ಮಾಹಿತಿ ಅಪ್‌ಡೇಟ್ ಮಾಡಿ.',
    'profile.full_name': 'ಪೂರ್ಣ ಹೆಸರು',
    'profile.full_name_placeholder': 'ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರು ನಮೂದಿಸಿ',
    'profile.phone_number': 'ಫೋನ್ ಸಂಖ್ಯೆ',
    'profile.location_title': 'ಸ್ಥಳ ವಿಳಾಸ ಮತ್ತು ಸೇವಾ ನಗರ',
    'profile.location_desc': 'ದೂರದ ಫಿಲ್ಟರ್‌ಗಳನ್ನು ಲೆಕ್ಕಾಚಾರ ಮಾಡಲು ಮತ್ತು ಹತ್ತಿರದ ಗ್ರಾಹಕರಿಗೆ ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ತೋರಿಸಲು ಬಳಸಲಾಗುತ್ತದೆ.',
    'profile.city_label': 'ನಗರ / ಕಾರ್ಯಾಚರಣೆ ಪ್ರದೇಶ',
    'profile.city_placeholder': 'ಉದಾ. ಮುಂಬೈ, ದೆಹಲಿ, ಬೆಂಗಳೂರು',
    'profile.mapping_gps': 'GPS ಮ್ಯಾಪಿಂಗ್...',
    'profile.auto_detect_gps': 'GPS ನಿರ್ದೇಶಾಂಕ ಸ್ವಯಂ-ಪತ್ತೆ',
    'profile.service_settings_title': 'ವೃತ್ತಿಪರ ಸೇವಾ ಪ್ರೊಫೈಲ್ ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    'profile.service_settings_desc': 'ಗ್ರಾಹಕರಿಗೆ ತೋರಿಸಲಾದ ವೃತ್ತಿ ವಿಶೇಷತೆ, ಗಂಟೆಯ ದರ, ಮತ್ತು ಸೇವಾ ತ್ರಿಜ್ಯವನ್ನು ಕಾನ್ಫಿಗರ್ ಮಾಡಿ.',
    'profile.select_trade': 'ವೃತ್ತಿ ವಿಶೇಷತೆ ಆಯ್ಕೆಮಾಡಿ',
    'profile.hourly_rate_label': 'ಗಂಟೆಯ ದರ (₹/ಗಂಟೆ)',
    'profile.experience_label': 'ಅನುಭವ (ವರ್ಷಗಳು)',
    'profile.radius_label': 'ಸೇವಾ ಪ್ರದೇಶ ತ್ರಿಜ್ಯ (ಕಿಮೀ)',
    'profile.availability_status': 'ಲಭ್ಯತೆ ಸ್ಥಿತಿ',
    'profile.availability_desc': 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಸಕ್ರಿಯ ಹುಡುಕಾಟ ಫಲಿತಾಂಶಗಳಲ್ಲಿ ಪಟ್ಟಿಮಾಡಲಾಗಿದೆಯೇ ಎಂಬುದನ್ನು ನಿಯಂತ್ರಿಸುತ್ತದೆ',
    'profile.bio_label': 'ವೃತ್ತಿಪರ ಪರಿಚಯ',
    'profile.bio_placeholder': 'ನಿಮ್ಮ ಸೇವಾ ಪರಿಣತಿ, ದುರಸ್ತಿ ಖಾತ್ರಿ, ಮತ್ತು ಅರ್ಹತೆಗಳನ್ನು ವಿವರಿಸಿ...',
    'profile.services_offered': 'ಕಸ್ಟಮೈಸ್ ಮಾಡಿದ ಸೇವೆಗಳು',
    'profile.services_offered_desc': 'ನಿಮ್ಮ ಪ್ರದೇಶದ ಮನೆಮಾಲೀಕರಿಗೆ ನೀವು ಯಾವ ವಿಶೇಷ ದುರಸ್ತಿ ಸೇವೆಗಳನ್ನು ನೀಡುತ್ತೀರಿ ಎಂಬುದನ್ನು ಆಯ್ಕೆಮಾಡಿ.',
    'profile.additional_custom': 'ಹೆಚ್ಚುವರಿ ಕಸ್ಟಮ್ ಸೇವೆಗಳು:',
    'profile.add_custom_placeholder': 'ಕಸ್ಟಮ್ ಸೇವೆ ಸೇರಿಸಿ (ಉದಾ. ಸ್ಮಾರ್ಟ್ ಲಾಕ್ ಇನ್‌ಸ್ಟಾಲೇಶನ್)...',
    'profile.add_service': '+ ಸೇವೆ ಸೇರಿಸಿ',
    'profile.saving': 'ಸೆಟ್ಟಿಂಗ್‌ಗಳನ್ನು ಉಳಿಸಲಾಗುತ್ತಿದೆ...',
    'profile.save_cta': 'ಪ್ರೊಫೈಲ್ ಮತ್ತು ಸೇವಾ ಸೆಟ್ಟಿಂಗ್‌ಗಳನ್ನು ಉಳಿಸಿ →',
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    if (typeof window !== 'undefined') {
      const saved = window.localStorage.getItem('fixitnow_lang') as Language;
      if (saved && (saved === 'en' || saved === 'hi' || saved === 'kn')) {
        setLanguageState(saved);
      }
    }
    setMounted(true);
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== 'undefined') {
      window.localStorage.setItem('fixitnow_lang', lang);
      window.dispatchEvent(new Event('fixitnow_lang_change'));
    }
  };

  // Always use 'en' until mounted to match server-rendered HTML
  const activeLang = mounted ? language : 'en';

  const t = (key: string): string => {
    const dict = TRANSLATIONS[activeLang];
    if (dict && dict[key]) {
      return dict[key];
    }
    // Fallback to English if translation is missing in the current language
    const fallbackDict = TRANSLATIONS['en'];
    return (fallbackDict && fallbackDict[key]) || key;
  };

  return (
    <LanguageContext.Provider value={{ language: activeLang, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
